server:
  port: 8088
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: onlineshop.project.spring@gmail.com
      password: ProgramareaAplicatiilorWeb2023CUNBM
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true